<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="TYSS-Chaithra" failures="1" tests="1" name="Default test" time="14.456" errors="0" timestamp="2022-03-30T15:38:44 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="14.062">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at âœ½.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
