<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Chaithra" failures="4" tests="4" name="runner.RunnerIO" time="125.067" errors="0" timestamp="2022-03-30T12:50:27 IST" skipped="0">
  <testcase classname="runner.RunnerIO" name="runScenario" time="17.305">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at ✽.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.RunnerIO" name="runScenario" time="18.602">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at ✽.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.RunnerIO" name="runScenario" time="17.637">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at ✽.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.RunnerIO" name="runScenario" time="71.523">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at stepDefinitions.DataDrivenTest.click_on_create_organization_lookm_up_image(DataDrivenTest.java:72)
at ✽.Click on create organization lookm up image(file:///D:/MavenProjects/Practice.BDD/./src/test/java/features/DataDriven.feature:18)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.RunnerIO -->
